### ISSUE TITLE
Only option for key is a file.  

### ISSUE THREAD

**Issue by rick-rheo** [ananay/apple-auth#11]
We use an internal service for stuff like secrets and keys etc. so that stuff like that doesn't sit developer's hard drives, in source repos, etc.   So there is no file, its a live request. You should have an initialization option that allows the user to provide the key directly.   Its actually bad practice to store stuff like that in simple files.

**Comment by rick-rheo** [comment]
Also, why do you want the config as a JSON string? Why not an object?

**Comment by ananay** [comment]
Hi @rick-rheo, you can pass an object instead of a JSON string in the parameters and it will still work. As for the key file, that is not under my control. Apple has provided you with a key file to generate the client secret and that is required. Also in your case, I would suggest that you setup a separate application for your development environment. That way you can keep your development and production keys separate.

As for the initialization option, you can store the key location in an environment variable or any other way and import it. Since this is a library, I feel it would be irrelevant to add that feature to the library itself. However, if you would like I can add it to https://github.com/ananay/apple-auth-example

**Comment by rick-rheo** [comment]
I tried passing an object and couldn't figure out why it failed until I read the code

https://github.com/ananay/apple-auth/blob/master/src/apple-auth.js#L29

and found it that it wants a string.


Regarding the key file.  Its a text file.  I know Apple requires it but what I'm saying is that your constructor should accept a string value containing the key.

**Comment by ananay** [comment]
Oops! Thanks for letting me know about this. I'll add type checking so you can pass in an object.

**Comment by rick-rheo** [comment]
Thanks!  And thank you for putting this library out. You saved me a ton of time and headache!

**Comment by ananay** [comment]
@rick-rheo I've implemented all the changes you suggested!
I just need to write the documentation for it now and then I can release it in the next version.

**Comment by ananay** [comment]
@rick-rheo Just a heads up, I've launched a new version of this library with the changes you requested. Please install the latest version from NPM if you would like these features.
